// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyu0Ss7kMmFmLFHtMuMgdEo5cxTrtro8',
    appId: '1:160268507071:web:15e2a82db77ea47b33330a',
    messagingSenderId: '160268507071',
    projectId: 'total-x-task-29b5e',
    authDomain: 'total-x-task-29b5e.firebaseapp.com',
    storageBucket: 'total-x-task-29b5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_CRj91HSElOtV-t2pSyoqe9EncdxEm5o',
    appId: '1:160268507071:android:bf517a9dd41d37ae33330a',
    messagingSenderId: '160268507071',
    projectId: 'total-x-task-29b5e',
    storageBucket: 'total-x-task-29b5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnX-_PyjuzoWommN6IHqF-gYiy9D2uxWc',
    appId: '1:160268507071:ios:65c58de85a2e5a7633330a',
    messagingSenderId: '160268507071',
    projectId: 'total-x-task-29b5e',
    storageBucket: 'total-x-task-29b5e.appspot.com',
    iosBundleId: 'com.example.totalxTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnX-_PyjuzoWommN6IHqF-gYiy9D2uxWc',
    appId: '1:160268507071:ios:65c58de85a2e5a7633330a',
    messagingSenderId: '160268507071',
    projectId: 'total-x-task-29b5e',
    storageBucket: 'total-x-task-29b5e.appspot.com',
    iosBundleId: 'com.example.totalxTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlyu0Ss7kMmFmLFHtMuMgdEo5cxTrtro8',
    appId: '1:160268507071:web:902fce3b464b8bad33330a',
    messagingSenderId: '160268507071',
    projectId: 'total-x-task-29b5e',
    authDomain: 'total-x-task-29b5e.firebaseapp.com',
    storageBucket: 'total-x-task-29b5e.appspot.com',
  );
}
