// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHfv57BVz0llLOpP2PkWPzLsYCJrXwhzU',
    appId: '1:649853049104:web:1cf8067fcd7357e542ed95',
    messagingSenderId: '649853049104',
    projectId: 'task-2-1d55a',
    authDomain: 'task-2-1d55a.firebaseapp.com',
    storageBucket: 'task-2-1d55a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQU5Ys5r5bRzF-hAe_wDdsuHt3qgoQlIM',
    appId: '1:649853049104:android:c309cc25922fd53c42ed95',
    messagingSenderId: '649853049104',
    projectId: 'task-2-1d55a',
    storageBucket: 'task-2-1d55a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj3HAivqw2NhM5r5C_7ETh4Jxdk3rrh0A',
    appId: '1:649853049104:ios:2324c1811e16682e42ed95',
    messagingSenderId: '649853049104',
    projectId: 'task-2-1d55a',
    storageBucket: 'task-2-1d55a.appspot.com',
    androidClientId: '649853049104-akmj2cgteoj90c2hj9ujc424g9ju5arv.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalxTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj3HAivqw2NhM5r5C_7ETh4Jxdk3rrh0A',
    appId: '1:649853049104:ios:2324c1811e16682e42ed95',
    messagingSenderId: '649853049104',
    projectId: 'task-2-1d55a',
    storageBucket: 'task-2-1d55a.appspot.com',
    androidClientId: '649853049104-akmj2cgteoj90c2hj9ujc424g9ju5arv.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalxTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHfv57BVz0llLOpP2PkWPzLsYCJrXwhzU',
    appId: '1:649853049104:web:1774d9fb9ddcd38f42ed95',
    messagingSenderId: '649853049104',
    projectId: 'task-2-1d55a',
    authDomain: 'task-2-1d55a.firebaseapp.com',
    storageBucket: 'task-2-1d55a.appspot.com',
  );
}
